### ISSUE TITLE
Invalid method Magento\Customer\Model\Address::isDefaultBilling

### ISSUE THREAD

**Issue by sivajik34** [instapunchout/magento2-punchout#1]
It seems issue related to customer_data_object_login event
$this->_eventManager->dispatch('customer_data_object_login', ['customer' => $customer]);

**Comment by oussama** [comment]
@sivajik34 yes, thanks that was the issue, I made an update in the login code for the latest magento version to use setCustomerAsLoggedIn instead of setCustomerDataAsLoggedIn so I hade to change the customer data object, to a customer object. which when passed to that event breaks things.
Fixed and deployed under tag 1.0.9.

**Comment by sivajik34** [comment]
Thank you
